---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fizu3884/sitesProjets/ravignon-enzo.fr

    - >
      /usr/bin/rsync -a --delete
      --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r
      --exclude='.git/'
      --exclude='.env'
      --exclude='.env.local'
      --exclude='var/'
      --exclude='error_log'
      --exclude='public/error_log'
      --exclude='public/uploads/'
      ./ "$DEPLOYPATH"/

    - chmod 711 "$DEPLOYPATH"
    - chmod 755 "$DEPLOYPATH/public"
    - if [ -f "$DEPLOYPATH/public/.htaccess" ]; then chmod 644 "$DEPLOYPATH/public/.htaccess"; fi

    - mkdir -p "$DEPLOYPATH/var" && chmod -R 775 "$DEPLOYPATH/var" || true
    - if [ -f "$DEPLOYPATH/.env.local" ]; then chmod 600 "$DEPLOYPATH/.env.local"; fi

    - cd "$DEPLOYPATH" && php /opt/cpanel/composer/bin/composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader --no-scripts
    - test -f "$DEPLOYPATH/vendor/autoload_runtime.php"
    - cd "$DEPLOYPATH" && APP_ENV=prod APP_DEBUG=0 php bin/console doctrine:migrations:migrate --no-interaction --env=prod
    - cd "$DEPLOYPATH" && APP_ENV=prod APP_DEBUG=0 php bin/console assets:install public --symlink --relative
    - cd "$DEPLOYPATH" && APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear --env=prod

